interfaces:
    - name: xe-0/0/2
      description: "connect bms4"
      vlan_id: 1
    - name: xe-0/0/3
      description: "connect cc1"
      vlan_id: 1
    - name: xe-0/0/4
      description: "connect cc2"
      vlan_id: 1

inet_interfaces:
    - name: xe-0/0/0
      ip: 10.0.6.2/30
      description: "connect to vqfx1"
    - name: xe-0/0/1
      ip: 10.0.2.2/30
      description: "connect to vqfx4"
    - name: irb
      description: "vRouter gateway for leaf srvs"
      ip: 172.16.5.1/24
    - name: lo0
      description: "vqfx Loopback"
      ip: 2.2.2.5/32

router_id: 2.2.2.5
overlay_asn: 64512
local_as: 64503
local_address: 2.2.2.5

peers:
    - name: spine1
      neighbor: 10.0.6.1
      peer_as: 64601
    - name: spine4
      neighbor: 10.0.2.1
      peer_as: 64602
