interfaces:
    - name: xe-0/0/2
      description: "connect bms4"
      vlan_id: 1
    - name: xe-0/0/3
      description: "connect vr6"
      vlan_id: 1

inet_interfaces:
    - name: xe-0/0/0
      ip: 10.0.7.2/30
      description: "connect to vqfx1"
    - name: xe-0/0/1
      ip: 10.0.3.2/30
      description: "connect to vqfx4"
    - name: irb
      description: "vRouter gateway for leaf srvs"
      ip: 172.16.6.1/24
    - name: lo0
      description: "vqfx Loopback"
      ip: 2.2.2.6/32

router_id: 2.2.2.6
overlay_asn: 64512
local_as: 64504
local_address: 2.2.2.6

peers:
    - name: spine1
      neighbor: 10.0.7.1
      peer_as: 64601
    - name: spine4
      neighbor: 10.0.3.1
      peer_as: 64602
